### PR TITLE
Confine the build to type resolution and emit declarations, not JavaScript (Closes #2983)

### LINKED ISSUE #2983: Remove the build from the test path; keep it for lint/typecheck only and emit declarations, not JS
## Parent

Sub-issue of #2702 (CI execution optimization). Supports #2578 (all-Bun).

## Objective

The build exists to serve type-aware lint and typecheck. Nothing else. Confine it accordingly, and stop emitting JavaScript nobody runs.

Two changes:

1. Remove `npm run build` from the test path. Tests do not read compiled output.
2. Reduce the retained build to declaration-only emit. Type resolution needs `.d.ts`; it does not need `.js`.

## Nothing but type resolution consumes the build

**Distribution does not.** The root `package.json` `files` array ships TypeScript source with no `dist/` entry: `packages/*/index.ts`, `packages/*/src/`, `packages/cli/bin/`, plus the install scripts. `packages/cli` declares `main: index.ts`. `prepack` runs `bun scripts/generate-git-commit-info.ts` and does not build. This is the no-compile npm runtime from #2243/#2305 and the bundled-Bun launcher from #2603/#2610, already merged.

**Tests do not.** Every workspace declares a `bun` export condition resolving to TypeScript source, at complete coverage:

| Package | entries with `bun` condition |
|---|---:|
| core | 123/123 |
| providers | 43/43 |
| tools | 41/41 |
| auth | 11/11 |
| agents | 4/4 |

Under Bun, cross-package imports resolve to `.ts` and never touch `dist/`. Vitest does not read it either: `packages/cli/vitest.config.ts` aliases cross-workspace imports directly to source (`../core/index.ts`, `../providers/index.ts`, `../storage/index.ts`, `../settings/index.ts`, `../ide-integration/index.ts`).

**Type-aware lint and typecheck do.** Three non-build tsconfigs map cross-workspace imports at compiled declarations:

    packages/cli/tsconfig.json:38-39
      @vybestack/llxprt-code-tools    -> ../tools/dist/index.d.ts
      @vybestack/llxprt-code-tools/*  -> ../tools/dist/src/*

    packages/core/tsconfig.json:16-17
      @vybestack/llxprt-code-mcp      -> ../mcp/dist/mcp/index.d.ts
      @vybestack/llxprt-code-mcp/*    -> ../mcp/dist/mcp/src/*

    packages/a2a-server/tsconfig.json:16-21
      @vybestack/llxprt-code-settings -> ../settings/dist/index.d.ts
      @vybestack/llxprt-code-storage  -> ../storage/dist/index.d.ts
      @vybestack/llxprt-code-tools    -> ../tools/dist/index.d.ts
      (plus matching /* wildcards)

Per-package `typecheck` is `tsc --noEmit`, which still requires those declarations to exist on disk to resolve.

Retaining a build to produce declarations is a deliberate choice, not an accident: mapping every cross-workspace import at source would make each typecheck re-analyze all transitive source across sixteen workspaces. Prebuilt declarations keep type checking bounded.

## Change 1 — remove the build from the test path

`.github/workflows/ci.yml:956` runs `npm run build` in every `test_shard` leg before tests execute. Tests resolve source, so this output is never read. With six shard legs this is the bulk of the measured eight `Build project` steps and 10.23 runner-minutes per full run.

Removing it also decouples shard count from build cost. Today, adding a shard to reduce test wall time adds another full build, partially cancelling the gain.

## Change 2 — emit declarations, not JavaScript

`scripts/build_package.ts:37-41` runs `tsc --build --clean` then `tsc --build` against each workspace tsconfig. The root `tsconfig.json:20` sets `declaration: true` with no `emitDeclarationOnly`, so every build emits both `.js` and `.d.ts`.

Since no runtime consumer reads the emitted JavaScript, the JavaScript emit is pure cost. Setting `emitDeclarationOnly` for the CI type-resolution build removes transpilation and JavaScript file writes while preserving exactly what lint and typecheck need.

Verify this does not break `scripts/copy_files.ts` (invoked at `build_package.ts:44`) or anything that assumes `.js` output exists on disk.

## Scope

- Remove `npm run build` from `test_shard` (`ci.yml:956`).
- Keep the build in the lint/typecheck job (`ci.yml:444`), which legitimately needs declarations.
- Correct the stale comment at `ci.yml:436-442`. It justifies the build by citing "storage, settings" as workspaces mapping to `dist/*.d.ts`; `packages/storage/tsconfig.json` maps all twelve of its paths to source and has no `dist` reference. The real dependents are cli to tools, core to mcp, and a2a-server to settings/storage/tools.
- Introduce declaration-only emit for the CI type-resolution build.
- Confirm `lint:agents-api-surface`, `lint:affected-shards`, and `gate:agents-neutral` still pass, since they run after the build and use the TypeScript compiler API.
- Confirm the release/packaging path (`ci.yml:1184`) still gets whatever it requires; if it needs full JavaScript emit, keep that variant confined to release.

## Out of scope

- Repointing the seven cross-workspace mappings at source. That would eliminate the build entirely but shifts type-checking cost into every typecheck run. Not being pursued; the build is retained deliberately for lint and typecheck.
- Changing what is published or how the CLI launches.

## Risks

- Some guard or script may assume `dist/*.js` exists. Declaration-only emit will surface that; fix the assumption rather than reinstating full emit blindly.
- Removing the build from shards may surface a test that quietly depended on compiled output. That dependency is a defect given the `bun` and Vitest alias resolution, and should be fixed at the import site.
- No new lint suppressions and no relaxed rules, per the standing guardrail.

## Acceptance criteria

- [ ] `npm run build` no longer runs in `test_shard`
- [ ] All shards pass with no `dist/` present at test time
- [ ] The retained lint/typecheck build emits declarations only, not JavaScript
- [ ] Type-aware lint, typecheck, and the API-surface/graph guards all pass
- [ ] The stale comment at `ci.yml:436-442` is corrected
- [ ] The release/packaging path still produces whatever it requires
- [ ] No new lint suppressions or rule relaxations
- [ ] Measured before/after recorded here: runner-minutes spent building, and critical-path wall time
- [ ] Full verification suite passes: test, lint, typecheck, format, build

## Relationship

Contributes to #2702 and #2578. Touches the same tsconfig surface as #2618 (tsconfig bypasses); coordinate to avoid conflict. Supersedes the artifact-sharing approach deferred by #2707/#2731, which is unnecessary once the build leaves the test path.

### PR DESCRIPTION
**Pull request by acoliver**
## TLDR

The TypeScript build exists to serve type-aware lint and `tsc --noEmit`. This PR confines it to that job.

- **Four of six `test_shard` legs stop building.** Tests never read compiled output: every workspace declares a `bun` export condition resolving to TypeScript source, and `packages/cli/vitest.config.ts` aliases cross-workspace imports at source.
- **The retained lint/typecheck build stops transpiling.** `npm run build:types` runs `tsc --build --emitDeclarationOnly`, producing 2771 `.d.ts` files and zero compiler-emitted JavaScript.
- **The release path is untouched.** `release.yml` still runs `npm run build:packages` with full emit, because every published library workspace declares `main: dist/index.js` and ships `dist`.

Removing the build surfaced four places that quietly depended on compiled output. All four are fixed at the import/spawn site rather than by restoring the build.

Reviewers should look hardest at two things: the decision to keep a build on the `agents` and `scripts` legs (explained below, with measurements), and the fact that a *partially* built workspace is worse than an unbuilt one under Bun.

### What actually consumes `packages/*/dist`

| Consumer | Reads `dist`? |
| --- | --- |
| Type-aware lint and `tsc --noEmit` | Yes — `cli -> tools`, `core -> mcp`, `a2a-server -> settings/storage/tools` map at `dist/*.d.ts` |
| npm consumers of the published library packages | Yes — `main`/`import` point at `dist/*.js` when a consumer resolves without the `bun` condition |
| The PR test path | No |
| The published CLI | No — raw TypeScript plus the separate publish-time bundle at `packages/cli/bundle/llxprt.js` (#2999 / #3013), which `prepack` builds and this PR never touches |

### Hidden consumers the change surfaced

Measured by deleting `packages/*/dist` and running every shard.

1. `scripts/start.ts` imported `parseBootstrapArgs` from `packages/cli/dist/src/config/profileBootstrap.js` and threw the result away. The call was added by the JS-to-TS script migration and duplicates what the spawned CLI already does. Removed.
2. Three CLI integration files spawned `node packages/cli/dist/index.js` (34 failing cases). Their own comments already described the child as booting from TypeScript source, so they now spawn `packages/cli/index.ts` with the Bun binary running the suite — which is what the shipped launcher does. They are also noticeably faster.
3. `packages/auth`'s package-boundary test asserted `dist/index.js` and `dist/index.d.ts` exist on disk. That only held because the shard built first, so it measured the CI harness. Its coverage is replaced by an end-to-end build test (below); the published contract stays pinned by the `main`/`types`/`exports` assertions in the same file.
4. `packages/cli`'s build chains `chmod_executable.ts dist/index.js`, which does not exist in declaration-only mode. The script now treats an absent target as a no-op **only** in that mode and still fails loudly otherwise.

### Why the `agents` and `scripts` legs still build

Both run the agents API-surface guard — `agents` through its package `pretest` hook, `scripts` through `scripts/tests/check-agents-api-surface.test.ts`. Despite its docblock, that guard needs dependency declarations: its temp tsconfig resolves `@vybestack/llxprt-code-{telemetry,mcp}` and several `storage/*` subpaths through `node_modules` to `dist/*.d.ts`, because `packages/agents/tsconfig.json` has no source mapping for them. Those subpaths are not expressible as wildcard `paths` entries — `@vybestack/llxprt-code-storage/storage/secure-store.js` resolves to `src/secure-store/secure-store.ts`, and `@vybestack/llxprt-code-tools/doubleEscapeUtils.js` to `src/formatters/doubleEscapeUtils.ts`. Repointing them is #2618, and the issue lists that work under **Out of scope**.

Everything else on those legs is fine without a build: with `dist` deleted, `bun scripts/test.ts --shard agents --skip-pretest` passes 337/340 files, and the three stragglers pass in isolation (they are load-sensitive 30s timeouts, not resolution failures).

The redundant per-shard `Run agents API-surface guard` step is removed: `lint_javascript` already runs it after its own build, and the `agents` shard covers it through the package `pretest` hook.

### Why those legs need the FULL build, not `build:types`

Bun applies tsconfig `paths` at runtime. `packages/core/tsconfig.json` maps `@vybestack/llxprt-code-mcp` to `../mcp/dist/mcp/index.d.ts`, and that mapping wins over the package's `bun` export condition whenever the file exists. With a declaration-only `dist`, cross-package imports therefore resolve to a `.d.ts` whose relative re-export has no JavaScript behind it.

Measured: 178 of 340 agents test files die at import with `Cannot find module './src/index.js' from packages/mcp/dist/mcp/index.d.ts`, and `bun scripts/start.ts` fails the same way. With **no** `dist`, resolution falls through to the `bun` condition and everything passes.

A complete `dist` works. No `dist` works. A partial one does not. `build:types` is therefore confined to `lint_javascript`, which executes no application code, and both `ci.yml` and the test suite pin that constraint so nobody moves it.

### Build plumbing

- `scripts/build_package.ts` appends `--emitDeclarationOnly` when `LLXPRT_EMIT_DECLARATIONS_ONLY=1`. Build mode accepts the flag, so no parallel tsconfig tree is needed — one pipeline, two emit modes. Only the exact value `1` enables it, so a stray `0` cannot change what the release build emits.
- Root `build:types` sets that variable and delegates to `build`. `build` and `build:packages` are untouched.
- `scripts/build.ts` skips two workspaces in declaration-only mode, because neither contributes declarations that any tsconfig maps: `vscode-ide-companion` ends its build in esbuild (which resolves workspace deps at `dist/*.js`), and `lsp` builds with a bare `tsc -p` that never sees the flag. Both still build normally on the release path, and `lsp` is reached at runtime by module resolution from a spawned process, never imported.

## Reviewer Test Plan

Confirm the emit contract:

    rm -rf packages/*/dist node_modules/.cache/tsbuildinfo
    npm run build:types
    find packages/*/dist -name '*.js' -o -name '*.js.map'

Only two files should appear, both example-extension assets copied verbatim by `copy_files.ts` (`examples/mcp-server/example.js`, `examples/hooks/scripts/on-start.js`). No compiler output. Then check `find packages/*/dist -name '*.d.ts' | wc -l` is in the thousands, and that lint and typecheck still pass against it:

    npm run typecheck
    npm run lint:ci
    npm run lint:agents-api-surface
    npm run lint:affected-shards
    npm run gate:agents-neutral

Confirm the shards no longer need a build:

    rm -rf packages/*/dist node_modules/.cache/tsbuildinfo
    bun scripts/test.ts --shard cli
    bun scripts/test.ts --shard core
    bun scripts/test.ts --shard providers
    bun scripts/test.ts --shard rest
    bun scripts/start.ts --profile-load <your profile> "write me a haiku and nothing else"

Confirm the release path is intact:

    npm run build
    ls -l packages/cli/dist/index.js        # present and mode 0755
    npm run bundle:cli                       # publish-time CLI bundle still builds
    npm run build:types                      # declaration build must not delete it
    ls -l packages/cli/bundle/llxprt.js

And the focused suite:

    bun test scripts/tests/issue-2983-declaration-build.test.ts

Note: run the CLI integration files through `bun scripts/test.ts --shard cli`, not a single combined `bun test a.ts b.ts c.ts`. The CLI runner spawns one process per file and the suite relies on that isolation for `LLXPRT_CONFIG_HOME`; sharing one process leaks settings between files. That is pre-existing and unrelated to this PR.

## Testing Matrix

|          | 🍏  | 🪟  | 🐧  |
| -------- | --- | --- | --- |
| npm run  | ✅  | ❓  | ❓  |
| npx      | ❓  | ❓  | ❓  |
| Docker   | ❓  | ❓  | ❓  |
| Podman   | ❓  | -   | -   |
| Seatbelt | ❓  | -   | -   |

Verified on macOS: `npm run test`, `npm run lint:ci`, `npm run lint:eslint-guard`, `npm run typecheck`, `npm run format:check`, `npm run build`, `npm run build:types`, `npm run bundle:cli`, and the CLI smoke run. Windows and Linux are covered by the CI matrix; the two platform-sensitive spots are `chmod_executable.ts` (already a no-op on Windows) and `build:types`, which uses `cross-env`.

## Linked issues / bugs

Closes #2983

Contributes to #2702 (CI execution optimization) and #2578 (all-Bun).
Coordinates with #2999 / #3013: the publish-time CLI bundle stays decoupled from the declaration build, and no build path deletes `packages/cli/bundle/`.
Blocked on #2618 for the last two shard builds.

## Summary by CodeRabbit

- **Build & CI**
  - Improved build workflows by separating declaration generation from full JavaScript builds.
  - Limited full builds to the workflows that require generated runtime files.

- **Bug Fixes**
  - Improved CLI integration test reliability by running TypeScript entry points directly.
  - Added handling for process-launch failures so tests complete with clear error results.

- **Tests**
  - Added comprehensive coverage for declaration-only builds, release builds, workspace selection, asset handling, and executable permissions.

### CODE REVIEW

File: scripts/build.ts [hunk 1]
```diff
@@ -18,27 +18,90 @@
...
+  'llxprt-code-vscode-ide-companion',
+  '@vybestack/llxprt-code-lsp',
+]);
+
+/**
+ * npm's package-name grammar. Names reach a shell command line below, so a
+ * name outside this grammar is rejected rather than interpolated.
+ */
+const PACKAGE_NAME_PATTERN =
+  /^(?:@[a-z0-9][a-z0-9._-]*\/)?[a-z0-9][a-z0-9._-]*$/;
```
[the remark this answers is not in the document]
Comment (acoliver) [reply scripts/build.ts]: Fixed. The pattern now accepts uppercase in both the scope and name segments.

Agreed on the substance, with one clarification about intent: the pattern is not there to enforce npm naming policy, it is there because the names are interpolated into a shell command line by workspaceBuildSelector(). Uppercase is shell-safe, so rejecting it bought nothing and could have thrown on a legacy name. npm refuses uppercase for *new* packages but still resolves existing ones, so validating against the stricter rule was wrong for a resolver.

The comment above the constant now says what it is for.

File: scripts/build.ts [hunk 2]
```diff
@@ -52,14 +115,38 @@ function sandboxAvailable(): boolean {
...
+    } catch (error) {
+      console.error(`Sandbox image build failed: ${messageOf(error)}`);
+      throw error;
+    }
+  }
+}
+
+if (import.meta.main) {
+  main();
 }
```
[the remark this answers is not in the document]
Comment (acoliver) [reply scripts/build.ts:161]: The contract change is intentional, and I verified nothing depended on the old behaviour. Adding a regression test as suggested.

Why it changed: declarationBuildWorkspaces() has to be importable so a test can pin which workspaces the declaration build skips. Without the guard, importing scripts/build.ts would run npm install, npm run generate and a full workspace build as a side effect of a unit test.

Why it is safe: nothing imports scripts/build.ts for its side effects. A repo-wide search for imports or requires of that path returns exactly one hit, the new test file, which imports it for the helper only. Every real caller invokes it as a process: the root build script is bun scripts/build.ts, and Makefile, release.yml, nightly.yml, e2e.yml, build-sandbox.yml and interactive-ui.yml all go through npm run build. That entry path is exercised on this PR by the agents and scripts shard legs, which run npm run build and passed.

Regression test added: a case spawns scripts/build_package.ts from a directory outside packages/ and asserts it exits 1 with must be invoked from a package directory. That check is the first statement inside the guarded main(), so reaching it proves the entry-point path still executes. The same guard pattern is already used by scripts/bun-build.config.ts, scripts/copy_bundle_assets.ts and packages/cli/run-bun-tests.ts.

File: scripts/tests/issue-2983-declaration-build.test.ts [hunk 3]
```diff
@@ -0,0 +1,524 @@
...
+  }, 240_000);
+});
+
+describe('issue #2983 — entry-point execution contract', () => {
+  // build_package.ts and build.ts now guard their bodies with
+  // `import.meta.main` so their helpers can be imported. Nothing in the repo
+  // imports either for side effects (this file imports build.ts purely for
+  // `declarationBuildWorkspaces`, and the suite performs no build as a
+  // result), but the spawned entry path must still run.
+  it('still runs build_package.ts when it is the entry point', () => {
```
[the remark this answers is not in the document]
Comment (acoliver) [reply scripts/tests/issue-2983-declaration-build.test.ts:259]: Added a parallel entry-point test for build.ts, with one correction to the suggested approach.

The suggestion was to spawn build.ts from outside packages/ and assert the same package-directory error. That would not work: build.ts has no cwd guard. It anchors its root on import.meta.url, not process.cwd(), so spawning it from a temp directory runs a real npm install, npm run generate and a full workspace build. The guard message the suggestion refers to lives only in build_package.ts.

The new case spawns build.ts with PATH pointed at an empty directory. Its first action inside the guarded main() is execSync of npm run generate, which then fails immediately with no npm on PATH. The test asserts a non-zero exit and that the output names npm run generate, which proves main() executed while doing no real work. execSync goes through an absolute /bin/sh, so an empty PATH does not prevent the shell from starting.

[the remark this answers is not in the document]
Comment (acoliver) [reply scripts/tests/issue-2983-declaration-build.test.ts:259]: Added a parallel entry-point test for build.ts, with one correction to the suggested approach.

The suggestion was to spawn build.ts from outside packages/ and assert the same package-directory error. That would not work: build.ts has no cwd guard. It anchors its root on import.meta.url, not process.cwd(), so spawning it from a temp directory runs a real npm install, npm run generate and a full workspace build. The guard message the suggestion refers to lives only in build_package.ts.

The new case spawns build.ts with PATH pointed at an empty directory. Its first action inside the guarded main() is execSync of npm run generate, which then fails immediately with no npm on PATH. The test asserts a non-zero exit and that the output names npm run generate, which proves main() executed while doing no real work. execSync goes through an absolute /bin/sh, so an empty PATH does not prevent the shell from starting.

[the remark this answers is not in the document]
Comment (acoliver) [reply scripts/tests/issue-2983-declaration-build.test.ts:259]: Added a parallel entry-point test for build.ts, with one correction to the suggested approach.

The suggestion was to spawn build.ts from outside packages/ and assert the same package-directory error. That would not work: build.ts has no cwd guard. It anchors its root on import.meta.url, not process.cwd(), so spawning it from a temp directory runs a real npm install, npm run generate and a full workspace build. The guard message the suggestion refers to lives only in build_package.ts.

The new case spawns build.ts with PATH pointed at an empty directory. Its first action inside the guarded main() is execSync of npm run generate, which then fails immediately with no npm on PATH. The test asserts a non-zero exit and that the output names npm run generate, which proves main() executed while doing no real work. execSync goes through an absolute /bin/sh, so an empty PATH does not prevent the shell from starting.

File: packages/cli/src/integration-tests/cli-args-test-helpers.ts [hunk 4]
```diff
@@ -118,6 +132,18 @@ export async function runCli(
...
+    // would hang until the runner's own timeout, hiding the cause.
+    child.on('error', (error: Error) => {
+      clearTimeout(timeout);
+      resolve({
+        stdout,
+        stderr: `${stderr}Failed to spawn ${CLI_ENTRY}: ${error.message}`,
+        exitCode: -1,
+      });
+    });
+
```
[the remark this answers is not in the document]
Comment (acoliver) [reply packages/cli/src/integration-tests/cli-args-test-helpers.ts:147]: Correct, and thanks for actually probing the runtime rather than asserting it. A spawn failure emits error and then close with a null exit code, so my comment was wrong about close never firing. The behaviour was already right — the first resolve wins and the later close cannot change a settled promise — but the comment described a different mechanism than the one at work.

Both comments now say that a spawn failure emits error and then close, that settling in the error handler preserves the spawn message and exit code -1, and that the later close cannot alter the already-settled promise. No behavioural change.

File: scripts/build.ts [hunk 5]
```diff
@@ -18,27 +18,92 @@
...
-const buildSandboxRequested =
-  process.env.BUILD_SANDBOX === '1' || process.env.BUILD_SANDBOX === 'true';
+function workspaceBuildSelector(): string {
+  if (!isDeclarationsOnly()) {
+    return '--workspaces';
+  }
+  return declarationBuildWorkspaces(readWorkspacePackageNames())
+    .map((name) => `--workspace=${name}`)
+    .join(' ');
+}
```
[the remark this answers is not in the document]
Comment (acoliver) [reply scripts/build.ts:113]: Good catch, applied. The silent-failure mode is the part that matters: an empty selector leaves a bare npm run build, which re-enters scripts/build.ts rather than fanning out to the workspaces, so the declaration build would appear to succeed while building nothing the way it intended.

workspaceBuildSelector now throws when the selection is empty, naming NON_DECLARATION_WORKSPACES so the cause is obvious. Agreed it is unreachable today; it becomes reachable the moment the exclusion set grows, and converting a silent wrong build into a loud failure is the right trade. Pinned by a test case in scripts/tests/issue-2983-declaration-build.test.ts.

**Comment by acoliver** [comment]
## Scope note: one acceptance criterion is intentionally not fully met

The issue asks that `npm run build` no longer run in `test_shard` and that **all** shards pass with no `dist/` present. This PR removes the build from four of six legs. The `agents` and `scripts` legs still build. That is a deliberate deferral, and here is the evidence behind it.

**Why those two legs.** Both run the agents API-surface guard — `agents` through its package `pretest` hook, `scripts` through `scripts/tests/check-agents-api-surface.test.ts`. Nothing else on either leg needs a build: with `dist` deleted, `bun scripts/test.ts --shard agents --skip-pretest` passes 337/340 files, and the three stragglers pass individually (load-sensitive 30s timeouts, not resolution failures).

**Why the guard needs it.** Its docblock claims it is clean-CI safe, but that is not true today. Its temp tsconfig extends `packages/agents/tsconfig.json`, which has no source mapping for `@vybestack/llxprt-code-telemetry` or `@vybestack/llxprt-code-mcp` and no correct one for several `storage/*` and `tools/*` subpaths, so those specifiers fall through to node resolution and land on `dist/*.d.ts`. Twenty distinct specifiers fail without a build.

**Why it is not a small fix.** The failing subpaths are not expressible as wildcard `paths` entries, because the published subpath and the source layout diverge:

    @vybestack/llxprt-code-storage/storage/secure-store.js  ->  src/secure-store/secure-store.ts
    @vybestack/llxprt-code-tools/doubleEscapeUtils.js       ->  src/formatters/doubleEscapeUtils.ts

Each needs an explicit per-subpath mapping across four packages. That is repointing cross-workspace mappings at source, which the issue lists under **Out of scope** and which #2618 owns. It also carries real risk: the guard compares against a checked-in API-surface snapshot, so changing how it resolves types can shift the parsed surface.

**Second constraint, discovered while implementing.** Those two legs must run the FULL build, not `build:types`. Bun applies tsconfig `paths` at runtime, so `packages/core/tsconfig.json`'s `@vybestack/llxprt-code-mcp -> ../mcp/dist/mcp/index.d.ts` mapping beats the package's `bun` export condition whenever the file exists. With a declaration-only `dist`, 178 of 340 agents test files die at import with `Cannot find module './src/index.js' from packages/mcp/dist/mcp/index.d.ts`. A complete `dist` works and no `dist` works; a partial one does not. `build:types` is therefore confined to `lint_javascript`, which runs no application code, and both `ci.yml` and the test suite pin that so nobody moves it.

**What was delivered.** Four of six shard legs stop building, the retained lint/typecheck build stops transpiling, and four genuine `dist/*.js` consumers were fixed at the import site rather than by restoring the build. Removing the last two builds is unblocked by #2618.

**Comment by acoliver** [comment]
Follow-up filed: #3104 — removes the last two test-shard builds once the agents API-surface guard resolves at source. Blocked by #2618, milestone 0.12.0.
