### ISSUE TITLE
Combined-process `bun test src/composition/` cross-contaminates module mocks (58 spurious failures, reproduces on pristine main)

### ISSUE THREAD

**Issue by acoliver** [vybestack/llxprt-code#3558]
## Observed

Running multiple composition test files in a single Bun process — `cd packages/providers && bun test src/composition/` — produces 58 failures via cross-file contamination (`mock.module`, `vi`, `process.env` bleed). Example failure: `aliasProviderFactory.authOnly.test.ts` fails with `setRuntimeSettingsService is not a function`.

## Analysis

- Proven reproducible on a **pristine `origin/main` worktree at 3e47fff55** with clean dependencies: the identical 58 failures appear, so this is not introduced by any recent change; it is a main-level pre-existing condition.
- The canonical CI path (`scripts/run_bun_tests.ts`) spawns one Bun process per file, which is why CI stays green — the bug only bites humans/agents running a directory-wide `bun test src/composition/` directly.
- Every file passes individually (26/26 composition files pass via the per-file runner).

## Impact

Misleading red runs during local verification; agents or contributors running the obvious `bun test src/composition/` command see 58 spurious failures and may chase ghosts (this happened during merge-conflict verification for #3549 tonight).

## Suggested direction (not pursued per dogfooding policy)

- Investigate Bun's `mock.module`/`vi` state isolation across files in one process (possibly a Bun bug worth reporting upstream), and/or
- Add a guard/README note in packages/providers pointing at the canonical per-file runner.

**Comment by acoliver** [comment]
Consolidated into #3505.

Read-only audit recommendation, for authorized triage execution:

Pristine-main reproduction reports 58 failures in a combined composition process while all 26 files pass separately. Same test-invocation isolation contract as #3505, but its package fixtures and counts are unique evidence that must survive.

Evidence: https://github.com/vybestack/llxprt-code/issues/3558; main scripts/run_bun_tests.ts:467,967; comparison #3505

Transfer composition reproduction, missing export symptom, 26-file independent success and runner/documentation options into #3505 before closing this issue.
