### ISSUE TITLE
Define and enforce isolated Bun test execution for sandbox and provider composition suites

### ISSUE THREAD

**Issue by acoliver** [vybestack/llxprt-code#3505]
## Problem

Running `bun test` with `sandbox-launch-lifecycle.test.ts` and `sandbox-seatbelt.test.ts` in the same bun process makes 13 seatbelt tests fail, while each file passes 47/0 and 4/0 in isolation.

Reproduced on `issue3450-3475` HEAD (`fa2acb860`) with the #3475 working-tree changes stashed, so the pollution pre-dates #3475:

```
bun test packages/cli/src/utils/sandbox-launch-lifecycle.test.ts packages/cli/src/utils/sandbox-seatbelt.test.ts
# 38 pass, 13 fail
```

Failing tests: the `#1456 Seatbelt network policy` table (12 cases) and `AC11: seatbelt spawn env carries no capability transport (#1954)`. Symptom: the harness `args`/`env` files are never written, e.g.

```
ENOENT: no such file or directory, open '/var/folders/.../T/seatbelt-1456-XXXXXX/args'
```

so `runSeatbeltSandbox` never spawns the stub `sess` — the earlier suite leaves shared state (environment variables or process-global configuration) that aborts launch preparation.

The same batch of five related suites (`sandbox-node-modules-preflight`, `sandbox-node-modules-lifecycle`, `sandbox-dependency-volumes`, `sandbox-launch-lifecycle`, `sandbox-seatbelt`) shows the same 13 failures; every file passes alone.

## Impact

Any verification or CI invocation that batches these files into one bun process reports failures that do not exist when files run individually, which wastes triage time and can mask real regressions.

## Notes

- Observed while verifying #3475; confirmed pre-existing via stash round-trip on the branch HEAD.
- Likely causes to investigate: `LLXPRT_SANDBOX_MOUNTS`/`SANDBOX_MOUNTS`/`LLXPRT_*_HOME` env leakage across `afterEach` restores, or a stub `sandbox-exec`/`sess` PATH shim left in place by the earlier suite.

## Additional provider-composition reproduction from #3558

Before closing #3558, preserve its pristine-main revision `3e47fff55`, the command `cd packages/providers && bun test src/composition/`, the 58 combined-process failures including `setRuntimeSettingsService is not a function`, and the finding that all 26 composition files pass individually. Keep the sandbox reproduction already recorded here: 13 seatbelt failures and missing harness args/env files when the lifecycle and seatbelt suites share one Bun process. These are distinct fixture witnesses for the same supported-invocation/isolation contract.

Choose and document one contract: either combined-file invocation is supported and both fixture families must restore their shared mock/environment state, or it is unsupported and contributors receive an actionable guard/documented per-file runner entrypoint rather than unexplained failures. Characterize both witnesses before claiming the issue fixed. Preserve independent per-file execution and result accounting.

Do not fold in #3504, which reports timer/stream interference through the normal agents workspace runner, or #3548, which reports inter-process port contention. Those require different discriminating tests.
