### PR TITLE
fix(agents): require runtime MessageBus for TaskTool subagents (Fixes #2320)

### LINKED ISSUE #2320: Tighten MessageBus seams for TaskTool subagents
## Summary

Follow up to #2312 / PR #2319. That PR correctly fixed the runtime failure by threading the active session/runtime MessageBus through TaskTool-launched subagents, but it intentionally left some seams looser than ideal so the bug fix could ship safely.

This task is to tighten those seams and clean up the architectural shape around MessageBus ownership for TaskTool and subagent runtime setup.

## Background

PR #2319 established the working runtime chain:

    Config.initialize({ messageBus })
      -> createToolRegistry(messageBus)
      -> registerAgentTools(..., messageBus)
      -> TaskTool dependencies include messageBus
      -> BaseDeclarativeTool stores and forwards messageBus during build
      -> TaskTool.createInvocation receives messageBus
      -> SubagentOrchestrator receives messageBus
      -> SubAgentScope.create receives overrides.messageBus
      -> non-interactive tool execution config passes it to getOrCreateScheduler

That correctly keeps Config.getOrCreateScheduler strict. The follow-up concern is that several new boundaries allow MessageBus to be undefined even though the production TaskTool-subagent path requires an explicit bus.

## Problem

The current implementation has a type-safety and architecture smell:

1. The production registry path requires a session MessageBus, but TaskTool-oriented types still model the dependency as optional.
2. Some tests explicitly bless the undefined MessageBus path, which can normalize an invalid production state.
3. Failure can be delayed until scheduler creation instead of being rejected at the boundary where TaskTool/subagent orchestration is assembled.
4. The code currently mixes two concepts that should be clearly separated:
   - the concrete core policy MessageBus needed by Config.getOrCreateScheduler
   - the tools-layer IToolMessageBus abstraction used by normal tool invocations

This is not a functional regression in PR #2319; it is a maintainability issue. The fix is to make the valid production contract explicit.

## Desired outcome

Tighten the TaskTool/subagent MessageBus seams so the required runtime/session MessageBus is enforced at production boundaries and the architecture makes ownership clear.

Concrete goals:

- Make TaskToolArgs.messageBus required for registry-created TaskTool instances.
- Make TaskToolDependencies.messageBus required for the normal production constructor path, unless a separate test-only/custom construction path is explicitly modeled.
- Remove or rewrite tests whose only assertion is that undefined MessageBus is passed through as acceptable production behavior.
- If BaseDeclarativeTool.createInvocation must keep an optional messageBus parameter because of the shared abstraction, add an early, explicit TaskTool-level failure when the bus is unexpectedly absent.
- Preserve Config.getOrCreateScheduler strictness. Do not add fallback MessageBus creation and do not restore any implicit global/session lookup.
- Clarify in types or helper names why TaskTool needs the concrete core MessageBus while normal tools continue to receive IToolMessageBus through the tools adapter.

## Architectural cleanup to consider

The architectural smell is that MessageBus ownership crosses package/layer boundaries in an implicit way:

- core owns Config and scheduler creation and requires the concrete policy MessageBus
- tools owns BaseDeclarativeTool and carries an optional bus slot for invocation building
- agents owns TaskTool and SubagentOrchestrator, which need the concrete bus for subagent scheduler setup
- the registry inversion seam bridges core to agents

That makes it easy for the type system to lose the guarantee that a scheduler-capable subagent path has a bus.

Potential cleanup approaches:

1. Introduce a named required dependency type for TaskTool runtime construction, for example TaskToolRuntimeDependencies, where messageBus is mandatory.
2. Keep any optional/custom/test construction type separate from production registration so tests cannot accidentally bless an invalid production state.
3. Consider a small adapter or named field that distinguishes coreSchedulerMessageBus from toolMessageBus to avoid confusing the concrete core MessageBus with IToolMessageBus.
4. Add one behavioral regression test that runs a non-interactive TaskTool-launched subagent through a normal tool execution path and asserts the scheduler receives the exact runtime/session MessageBus.

## Acceptance criteria

- TypeScript prevents registry-created TaskTool instances from omitting the session/runtime MessageBus.
- No fallback MessageBus is created silently.
- Config.getOrCreateScheduler still throws when called without explicit dependencies.messageBus.
- Tests no longer present undefined MessageBus as normal for production TaskTool-launched subagents.
- A behavioral test or stronger near-end-to-end regression covers non-interactive TaskTool-launched subagent tool execution with the exact session MessageBus.
- Full verification passes: npm run test, npm run lint, npm run typecheck, npm run format, npm run build, and the standard ollamakimi smoke test.

### PR DESCRIPTION
**Pull request by acoliver**
## TLDR

Require registry-created `TaskTool` instances and `SubagentOrchestrator` instances to receive a concrete session/runtime `MessageBus`. The same bus is now preserved through non-interactive subagent tool scheduling, while the tools-layer `IToolMessageBus` invocation seam remains unchanged.

## Dive Deeper

The registry already receives the active session bus, but the agents-facing types allowed it to become optional. This change makes `TaskToolArgs.messageBus`, `TaskToolDependencies.messageBus`, the injected orchestrator factory argument, and `SubagentOrchestratorOptions.messageBus` required.

`TaskTool` retains a runtime boundary check for JavaScript and type-erased callers. It does not create a fallback bus or read one from `Config`, process state, or another implicit owner. `Config.getOrCreateScheduler` remains strict when no explicit bus is supplied.

The tests now provide a concrete bus at direct TaskTool and orchestrator construction sites. New and strengthened coverage verifies:

- malformed TaskTool construction fails before invocation or scheduler creation;
- the registry preserves the exact bus object;
- injected orchestrator factories receive that same object;
- a non-interactive TaskTool-launched subagent reaches a normal tool scheduler through the session bus, while a decoy bus receives no policy event;
- scheduler creation without an explicit bus still fails.

The test audit scanned 2,700 files with no scanner errors. Its normalized comparison against `origin/main` found no branch-only findings.

## Reviewer Test Plan

1. Run the focused MessageBus suites:
   ```bash
   bun test packages/agents/src/tools/task.test.ts packages/agents/src/tools/task.message-bus.integration.test.ts packages/core/src/config/config.agentInversion.test.ts packages/core/src/config/config.scheduler.test.ts packages/agents/src/core/subagentOrchestrator.test.ts
   ```
2. Confirm `TaskToolDependencies.messageBus`, `TaskToolArgs.messageBus`, and `SubagentOrchestratorOptions.messageBus` reject omission during `npm run typecheck`.
3. Inspect the integration test's session and decoy bus assertions. The policy rejection from a normal non-interactive subagent tool call must appear only on the session bus.
4. Run the standard verification commands and the `stepfun-37` smoke prompt.

## Testing Matrix

|          | 🍏 | 🪟 | 🐧 |
| -------- | --- | --- | --- |
| npm run  | ⚠️ | ❓ | ❓ |
| npx      | ❓ | ❓ | ❓ |
| Docker   | ❓ | ❓ | ❓ |
| Podman   | ❓ | - | - |
| Seatbelt | ❓ | - | - |

macOS verification:

- `npm run lint`: passed
- `npm run typecheck`: passed
- `npm run format`: passed
- `npm run build`: passed
- focused source tests: 198 passed, 0 failed
- affected standalone Bun tests: 21 passed, 0 failed
- `bun scripts/start.ts --profile-load stepfun-37 "write me a haiku and nothing else"`: passed
- `npm run test`: did not complete successfully. One run reached core and hit 180-second file timeouts in the changed `config.agentInversion.test.ts` and unchanged `SessionLockManager.lazy.test.ts`; those files passed together directly (12 passed, 0 failed). A clean-PATH rerun stopped after unchanged `grep-ripgrep-issue3203-remediation.test.ts` hit its 15-second test timeout; that file passed directly (21 passed, 0 failed).

## Linked issues / bugs

Fixes #2320

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved message delivery consistency during task execution and subagent scheduling.
  - Added validation to prevent task or scheduler creation when required messaging context is unavailable.
  - Ensured task events, including rejected actions, are routed through the active session messaging channel.
  - Improved reliability of task execution across asynchronous, streaming, timeout, and heartbeat scenarios.

- **Tests**
  - Expanded coverage for messaging context propagation, configuration errors, and task execution workflows.

### CODE REVIEW

**Comment by acoliver** [comment]
Review thread resolutions:

- Accepted the integration-test identity finding. Commit c682e180a now asserts that the `orchestratorFactory` argument is the same `sessionMessageBus` object before constructing `SubagentOrchestrator`.
- Declined the proposed `instanceof MessageBus` check. The runtime boundary guarantees that the required dependency is present; TypeScript enforces its concrete type for supported callers. An `instanceof` check would create package-copy and realm sensitivity and would broaden #2320 into arbitrary runtime object validation. The existing nullish guard covers the absent-dependency failure described by the issue.
