### ISSUE TITLE
BeforeToolSelection toolChoice.mode is decoded/aggregated/documented but not enforced on the outgoing request

### ISSUE THREAD

**Issue by acoliver** [vybestack/llxprt-code#3688]
Found during the #2624 review (finding LOW-3). The v2 BeforeToolSelection hook contract (`toolChoice {mode: 'auto'|'required'|'none', allowedToolNames?}`) is decoded, aggregated (none-wins + allowlist intersection), and documented in `docs/hooks/api-reference.md`, but the runtime only consumes `allowedToolNames` at the fire sites (`packages/agents/src/core/streamRequestHelpers.ts` ~145, `TurnProcessor.ts` ~826, `DirectMessageProcessor.ts` ~628). The `mode` value has no downstream effect on the provider request.

v1 behaved identically (Gemini `AUTO|ANY|NONE` was also accepted-but-unenforced), so this is not a regression from #2624 — but the v2 docs now describe semantics the runtime does not implement, which can mislead hook authors writing `mode: 'none'` or `mode: 'required'` hooks.

Options: either enforce mode when building the outgoing request (map to the provider's tool-choice settings via `ModelGenerationSettings.toolChoice`), or explicitly document that only `allowedToolNames` is enforced today. Discovered 2026-09-14 on the branch-4 checkout; review report at `tmp/issue2624-review/review-report.md`.
