### ISSUE TITLE
Tighten MessageBus seams for TaskTool subagents

### ISSUE THREAD

**Issue by acoliver** [vybestack/llxprt-code#2320]
## Summary

Follow up to #2312 / PR #2319. That PR correctly fixed the runtime failure by threading the active session/runtime MessageBus through TaskTool-launched subagents, but it intentionally left some seams looser than ideal so the bug fix could ship safely.

This task is to tighten those seams and clean up the architectural shape around MessageBus ownership for TaskTool and subagent runtime setup.

## Background

PR #2319 established the working runtime chain:

    Config.initialize({ messageBus })
      -> createToolRegistry(messageBus)
      -> registerAgentTools(..., messageBus)
      -> TaskTool dependencies include messageBus
      -> BaseDeclarativeTool stores and forwards messageBus during build
      -> TaskTool.createInvocation receives messageBus
      -> SubagentOrchestrator receives messageBus
      -> SubAgentScope.create receives overrides.messageBus
      -> non-interactive tool execution config passes it to getOrCreateScheduler

That correctly keeps Config.getOrCreateScheduler strict. The follow-up concern is that several new boundaries allow MessageBus to be undefined even though the production TaskTool-subagent path requires an explicit bus.

## Problem

The current implementation has a type-safety and architecture smell:

1. The production registry path requires a session MessageBus, but TaskTool-oriented types still model the dependency as optional.
2. Some tests explicitly bless the undefined MessageBus path, which can normalize an invalid production state.
3. Failure can be delayed until scheduler creation instead of being rejected at the boundary where TaskTool/subagent orchestration is assembled.
4. The code currently mixes two concepts that should be clearly separated:
   - the concrete core policy MessageBus needed by Config.getOrCreateScheduler
   - the tools-layer IToolMessageBus abstraction used by normal tool invocations

This is not a functional regression in PR #2319; it is a maintainability issue. The fix is to make the valid production contract explicit.

## Desired outcome

Tighten the TaskTool/subagent MessageBus seams so the required runtime/session MessageBus is enforced at production boundaries and the architecture makes ownership clear.

Concrete goals:

- Make TaskToolArgs.messageBus required for registry-created TaskTool instances.
- Make TaskToolDependencies.messageBus required for the normal production constructor path, unless a separate test-only/custom construction path is explicitly modeled.
- Remove or rewrite tests whose only assertion is that undefined MessageBus is passed through as acceptable production behavior.
- If BaseDeclarativeTool.createInvocation must keep an optional messageBus parameter because of the shared abstraction, add an early, explicit TaskTool-level failure when the bus is unexpectedly absent.
- Preserve Config.getOrCreateScheduler strictness. Do not add fallback MessageBus creation and do not restore any implicit global/session lookup.
- Clarify in types or helper names why TaskTool needs the concrete core MessageBus while normal tools continue to receive IToolMessageBus through the tools adapter.

## Architectural cleanup to consider

The architectural smell is that MessageBus ownership crosses package/layer boundaries in an implicit way:

- core owns Config and scheduler creation and requires the concrete policy MessageBus
- tools owns BaseDeclarativeTool and carries an optional bus slot for invocation building
- agents owns TaskTool and SubagentOrchestrator, which need the concrete bus for subagent scheduler setup
- the registry inversion seam bridges core to agents

That makes it easy for the type system to lose the guarantee that a scheduler-capable subagent path has a bus.

Potential cleanup approaches:

1. Introduce a named required dependency type for TaskTool runtime construction, for example TaskToolRuntimeDependencies, where messageBus is mandatory.
2. Keep any optional/custom/test construction type separate from production registration so tests cannot accidentally bless an invalid production state.
3. Consider a small adapter or named field that distinguishes coreSchedulerMessageBus from toolMessageBus to avoid confusing the concrete core MessageBus with IToolMessageBus.
4. Add one behavioral regression test that runs a non-interactive TaskTool-launched subagent through a normal tool execution path and asserts the scheduler receives the exact runtime/session MessageBus.

## Acceptance criteria

- TypeScript prevents registry-created TaskTool instances from omitting the session/runtime MessageBus.
- No fallback MessageBus is created silently.
- Config.getOrCreateScheduler still throws when called without explicit dependencies.messageBus.
- Tests no longer present undefined MessageBus as normal for production TaskTool-launched subagents.
- A behavioral test or stronger near-end-to-end regression covers non-interactive TaskTool-launched subagent tool execution with the exact session MessageBus.
- Full verification passes: npm run test, npm run lint, npm run typecheck, npm run format, npm run build, and the standard ollamakimi smoke test.

**Comment by acoliver** [comment]
Cross-link from architecture epic #2619: #3222 moves isolated/subagent assembly to the agent-owned path, but this issue remains authoritative for the exact MessageBus seam. The shared invariant is that each agent/session runtime explicitly supplies the intended concrete bus to scheduler/TaskTool/subagent creation; no implicit fallback bus or host-owned substitute should be introduced.
